### ISSUE TITLE
Send nmea via BT Esp32

### ISSUE THREAD

**Issue by XCNav** [ra1fh/airtraffic#1]
Most of the Apps running on a mobile Device supporting BT and or WiFi. Make it usable on a ESP32 devboard as BT emitter, wich is very cheap and easy to get. So in XCSoar, LK8000 or whatever simply select the esp as source getting nmea or gdl data

**Comment by ra1fh** [comment]
Thanks for the feedback!

This is intentionally targeting a Unix/POSIX environment to be able to quickly modify the traffic scenario and see the result right away. I have some doubts whether mruby/ESP32 would be capable of that, especially running the ESP32 in AP mode. Maybe MicroPython/CircuitPython could world, but that would be require a rewrite.

The next best option that would still qualify as cheap would be an OpenWRT capable device (e.g. gl.inet). I was actually thinking about trying that for a demo the other day. I will update the README with some instructions once I found time to look into that.

**Comment by ra1fh** [comment]
The latest version (4671b02fb15d60be9b91a90651370ec518f25a61) runs fine on OpenWRT devices with 16MB flash.  Those can be found for about $30/€30. Not as cheap as ESP32, but also not too far away from ESP32 dev boards either. That's the best I can do for now.

This was achieved by removing the EventMachine dependency. Compiling the EventMachine native extension would have required a rather large and expensive OpenWRT device to fit all dependencies into flash and have sufficient main memory for the compiler. And then, EventMachine is not well maintained, so this is good change anyway.

**Comment by XCNav** [comment]
O.k...thank you...i will try.
