### ISSUE TITLE
Negative lon

### ISSUE THREAD

**Issue by d3mac123** [ra1fh/airtraffic#3]
First of all, this is AWESOME!!!

I am trying to edit the airtraffic.rb file to add closer lat/lon (I am in the USA) but I am getting the following error when I enter a negative longitude (for example, -8):

`#<Thread:0x0000000126bc7880 ./airtraffic.rb:761 run> terminated with exception (report_on_exception is true):
./airtraffic.rb:705:in `pack_latlon': undefined local variable or method `latitude' for an instance of Gdl90Protocol (NameError)

            l = (0x1000000 + latitude) & 0xffffff
                             ^^^^^^^^
	from ./airtraffic.rb:607:in `msg_10_20'
	from ./airtraffic.rb:554:in `msg_ownship'
	from ./airtraffic.rb:649:in `message'
	from ./airtraffic.rb:766:in `block (2 levels) in run'
	from <internal:kernel>:187:in `loop'
	from ./airtraffic.rb:763:in `block in run'
error: undefined local variable or method `latitude' for an instance of Gdl90Protocol`

How can I enter negative lat/lon?

**Comment by ra1fh** [comment]
Thanks for the bug report! This is fixed in master branch now.
There was another issue when crossing the 180th meridian which is fixed as well.

**Comment by d3mac123** [comment]
Thank for the hard work. However, it seems things are a bit off. For example, I entered the following data for the default scene:
`DEFAULT_SCENE = "---
ownship:
  { id: 'N543WC', lat: 34.047178240549286, lon: -84.64612264640544, alt: 2000, speed: 80, direction: 90 }

traffic:
  - { id: 'N11EL', address: 0xaa5501, lat: 34.04, lon: -84.67, alt: 3100, speed: 110, direction: 1 }
  - { id: 'N21EL', address: 0xaa5502, lat: 34.047178240549286, lon: -84.68, alt: 2300, speed: 120, direction: 45 }
  - { id: 'N31EL', address: 0xaa5503, lat: 34.0471782405492866, lon: -84.70, alt: 2700, speed: 130, direction: 180 }
  - { id: 'N41EL', address: 0xaa5504, lat: 34.0471782405492866, lon: -84.72, alt: 4500, speed: 140, direction: 225 }
  - { id: 'N51EL', address: 0xaa5505, lat: 34.047178240549286, lon: -84.74, alt: 5000, speed: 150, direction: 289 }
  - { id: 'N61EL', address: 0xaa5506, lat: 33.92, lon: -8.64, alt: 7000, speed: 80, direction: 000, bearingless: true }"`

Attached what I am seeing:
![IMG_5923](https://github.com/user-attachments/assets/750735d9-bbd1-4cad-9de4-451e7b332ab4)
![IMG_5924](https://github.com/user-attachments/assets/8ad8412d-a43b-44ec-b2f2-c632704daaaa)
![IMG_5925](https://github.com/user-attachments/assets/8ab152b4-85ed-44af-8430-d6fab2e49f2e)

As you can see, aircraft N11EL, N41EL, N51EL and N61EL are not showing up (maybe I entered something wrong?). 

But, the most weird results are with the altitude calculations. As "my plane" is flying at 2000ft and N21EL is at 2300ft, shouldn't Foreflight (picture) show the airplane at 2300ft (300ft above me), instead of showing it is flying at 7525ft (900ft above me)?

The same applies for N31EL. Foreflight shows it is flying at 8850ft (instruction was 2700ft), 2200ft above me (shouldn't be 1200ft)?

**Comment by ra1fh** [comment]
You probably have "Hide Distant Traffic" enabled in Foreflight (that's in Settings->Traffic). When disabling that I can see most of the aircraft.

N61EL in your example seems to have a typo (lon: -8.64 instead of lon: -84.64 I guess). So it's close to the west coast of Africa and somewhat hard to find.

There is indeed something off with altitudes. The altitudes in the configuration are meant to be metric (although I haven't mentioned that anywhere). FLARM output is metric as well. But GDL90 wants feet. Let me check and get back to you.

**Comment by d3mac123** [comment]
Thanks again! While addressing the gdl90 part, also look at speeds to see if they require knots or miles per hour.

**Comment by ra1fh** [comment]
Speeds were consistent, in knots.

I have added support for unit suffixes now, which allows to make the configuration more clear. E.g. your example could be changed like this:

```
DEFAULT_SCENE = "---
ownship:
  { id: 'N543WC', lat: 34.047178240549286, lon: -84.64612264640544, alt: 2000_ft, speed: 80_kt, direction: 90 }

traffic:
  - { id: 'N11EL', address: 0xaa5501, lat: 34.04, lon: -84.67, alt: 3100_ft, speed: 110_kt, direction: 1 }
  - { id: 'N21EL', address: 0xaa5502, lat: 34.047178240549286, lon: -84.68, alt: 2300_ft, speed: 120_kt, direction: 45 }
  - { id: 'N31EL', address: 0xaa5503, lat: 34.0471782405492866, lon: -84.70, alt: 2700_ft, speed: 130_kt, direction: 180 }
  - { id: 'N41EL', address: 0xaa5504, lat: 34.0471782405492866, lon: -84.72, alt: 4500_ft, speed: 140_kt, direction: 225 }
  - { id: 'N51EL', address: 0xaa5505, lat: 34.047178240549286, lon: -84.74, alt: 5000_ft, speed: 150_kt, direction: 289 }
  - { id: 'N61EL', address: 0xaa5506, lat: 33.92, lon: -8.64, alt: 7000_ft, speed: 80_kt, direction: 000, bearingless: true }"
```

The default scene includes examples for all possible units.

**Comment by d3mac123** [comment]
I'll test first thing in the morning tomowwor. Thanks again!!!!!!
